object Versions {
    const val coreVersion = "1.7.0"
    const val appCompatVersion = "1.4.1"
    const val materialVersion = "1.5.0"
    const val constraintLayoutVersion = "2.1.3"
    const val jUnitVersion = "4.13.2"
    const val jUnitTestVersion = "1.1.3"
    const val espressoVersion = "3.4.0"
    const val applicationVersion = "7.1.0"
    const val libraryVersion = "7.1.0"
    const val kotlinVersion = "1.6.10"
    const val navigationVersion = "2.4.1"
    const val roomVersion = "2.4.1"
    const val hiltVersion = "2.40.5"
    const val coroutineVersion = "1.5.2"
    const val workVersion = "2.7.1"
    const val viewPagerVersion = "1.0.0"
    const val lifecycleVersion = "2.4.1"
    const val ktxVersion = "1.4.1"
    const val ktxActivityVersion = "1.4.0"
    const val timberVersion = "5.0.1"
    const val loggerVersion = "2.2.0"
    const val appProviderVersion = "1.4.0"
    const val powerSpinner = "1.1.9"

}